target = "aws-kms-key-arn.txt#section-2.5"

# 2.5.  A valid AWS KMS ARN
#
# A string with 5 ":" that delimit following 6 parts:
# 
# 1.  MUST start with string "arn"
# 
# 2.  The partition MUST be a non-empty
# 
# 3.  The service MUST be the string "kms"
# 
# 4.  The region MUST be a non-empty string
# 
# 5.  The account MUST be a non-empty string
# 
# 6.  The resource section MUST be non-empty. It MUST be split by a
#     single "/" any additional "/" are included in the resource id
# 
#     1.  The resource type MUST be either "alias" or "key"
# 
#     2.  The resource id MUST be a non-empty string

[[spec]]
level = "MUST"
quote = '''
MUST start with string "arn"
'''

[[spec]]
level = "MUST"
quote = '''
The partition MUST be a non-empty
'''

[[spec]]
level = "MUST"
quote = '''
The service MUST be the string "kms"
'''

[[spec]]
level = "MUST"
quote = '''
The region MUST be a non-empty string
'''

[[spec]]
level = "MUST"
quote = '''
The account MUST be a non-empty string
'''

[[spec]]
level = "MUST"
quote = '''
The resource section MUST be non-empty.
'''

[[spec]]
level = "MUST"
quote = '''
It MUST be split by a
single "/" any additional "/" are included in the resource id
'''

[[spec]]
level = "MUST"
quote = '''
The resource type MUST be either "alias" or "key"
'''

[[spec]]
level = "MUST"
quote = '''
The resource id MUST be a non-empty string
'''

