name: ci

on: 
  pull_request:
  push:
    branches:
      - main

jobs:

  steps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install txm for running test
      run: npm install txm
    
    - run: make install_dependencies
    - run: make all
  
  container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and run dev container task
      uses: devcontainers/ci@v0.2
      with:
        runCmd: |
          make verify_complete
          make assert_unchanged
